# MARCA_SELECT_MAIS_MODELOS_20260901
BRANDS = {
    'Volkswagen': ['Gol', 'Gol G2', 'Gol G3', 'Gol G4', 'Gol G5', 'Gol G6', 'Gol G7', 'Voyage', 'Saveiro', 'Saveiro Cross', 'Parati', 'Santana', 'Polo', 'Virtus', 'T-Cross', 'Nivus', 'Fox', 'CrossFox', 'SpaceFox', 'Jetta', 'Golf', 'Bora', 'Amarok', 'Kombi', 'Fusca', 'Up', 'Taos', 'Tiguan', 'Passat', 'Pointer', 'Logus', 'Apollo', 'Brasília'],
    'Chevrolet': ['Celta', 'Corsa', 'Corsa Sedan', 'Classic', 'Prisma', 'Onix', 'Onix Plus', 'Joy', 'Montana', 'S10', 'Tracker', 'Spin', 'Cruze', 'Astra', 'Vectra', 'Meriva', 'Zafira', 'Agile', 'Cobalt', 'Kadett', 'Monza', 'Omega', 'Blazer', 'Captiva', 'Sonic', 'Ipanema', 'Chevette', 'Opala', 'Caravan', 'D10', 'D20', 'Silverado', 'Trailblazer'],
    'Fiat': ['Uno', 'Uno Mille', 'Mobi', 'Palio', 'Palio Weekend', 'Siena', 'Grand Siena', 'Strada', 'Toro', 'Argo', 'Cronos', 'Punto', 'Idea', 'Fiorino', 'Doblò', 'Linea', 'Pulse', 'Fastback', 'Tipo', 'Tempra', 'Brava', 'Bravo', 'Stilo', '500', '147', 'Ducato', 'Elba', 'Prêmio', 'Freemont', 'Weekend'],
    'Ford': ['Ka', 'Ka Sedan', 'Fiesta', 'Fiesta Sedan', 'Focus', 'Focus Sedan', 'Fusion', 'EcoSport', 'Ranger', 'Maverick', 'Courier', 'F-250', 'Edge', 'Territory', 'Escort', 'Verona', 'Del Rey', 'Corcel', 'Belina', 'Pampa', 'Versailles', 'Mondeo', 'Mustang', 'F-1000', 'F-4000', 'Cargo', 'Transit', 'Explorer'],
    'Hyundai': ['HB20', 'HB20S', 'HB20X', 'Creta', 'Tucson', 'ix35', 'Santa Fe', 'Azera', 'i30', 'Elantra', 'Sonata', 'Veloster', 'HR', 'H100', 'Kona'],
    'Toyota': ['Etios', 'Etios Sedan', 'Yaris', 'Yaris Sedan', 'Corolla', 'Corolla Cross', 'Hilux', 'SW4', 'RAV4', 'Camry', 'Bandeirante', 'Prius', 'Fielder', 'Corona', 'Land Cruiser'],
    'Honda': ['Fit', 'City', 'Civic', 'HR-V', 'WR-V', 'CR-V', 'Accord', 'Civic Si', 'ZR-V'],
    'Renault': ['Kwid', 'Sandero', 'Stepway', 'Logan', 'Duster', 'Duster Oroch', 'Captur', 'Clio', 'Fluence', 'Megane', 'Scénic', 'Kangoo', 'Master', 'Symbol', 'Laguna'],
    'Peugeot': ['106', '205', '206', '207', '208', '2008', '3008', '307', '308', '408', 'Partner', 'Boxer', 'Hoggar', 'RCZ'],
    'Citroën': ['C3', 'C3 Aircross', 'C4', 'C4 Lounge', 'C4 Cactus', 'Aircross', 'Xsara Picasso', 'C3 Picasso', 'Berlingo', 'Jumper', 'Jumpy', 'C5'],
    'Nissan': ['March', 'Versa', 'Kicks', 'Frontier', 'Sentra', 'Livina', 'Grand Livina', 'Tiida', 'X-Trail', 'Altima', 'Pathfinder'],
    'Jeep': ['Renegade', 'Compass', 'Commander', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
    'Mitsubishi': ['L200', 'L200 Triton', 'Pajero', 'Pajero TR4', 'ASX', 'Outlander', 'Eclipse Cross', 'Airtrek', 'Lancer', 'Mirage'],
    'Kia': ['Picanto', 'Cerato', 'Soul', 'Sportage', 'Sorento', 'Bongo', 'Carnival', 'Carens', 'Optima', 'Mohave'],
    'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'GLA', 'GLC', 'Sprinter', 'Accelo', 'Atego', 'Axor', 'Actros', '1113', '1313', '1620'],
    'BMW': ['Série 1', 'Série 3', 'Série 5', 'Série 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'Z4', 'M3', 'M5'],
    'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'Q3', 'Q5', 'Q7', 'TT', 'RS3'],
    'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'V40', 'FH', 'FM', 'VM', 'NL', 'N10', 'N12'],
    'RAM': ['Rampage', '1500', '2500', '3500', 'Classic'],
    'Caoa Chery': ['QQ', 'Tiggo 2', 'Tiggo 3x', 'Tiggo 5x', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Arrizo 6', 'Celer', 'Face'],
    'BYD': ['Dolphin', 'Dolphin Mini', 'Song Plus', 'Yuan Plus', 'Seal', 'Han', 'Tan', 'King', 'Shark'],
    'GWM': ['Haval H6', 'Ora 03', 'Poer', 'Tank 300'],
    'Jac': ['J2', 'J3', 'J5', 'J6', 'T40', 'T50', 'T60', 'T80', 'iEV20', 'iEV40'],
    'Land Rover': ['Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Freelander', 'Defender'],
    'Subaru': ['Forester', 'Impreza', 'XV', 'Outback', 'Legacy', 'WRX', 'Tribeca'],
    'Suzuki': ['Jimny', 'Vitara', 'Grand Vitara', 'S-Cross', 'Swift', 'SX4', 'Samurai'],
    'Iveco': ['Daily', 'Tector', 'Stralis', 'Hi-Way', 'Eurocargo'],
    'Scania': ['P', 'G', 'R', 'S', '113', '124', 'P360', 'R440', 'R450', 'R480'],
    'MAN': ['Constellation', 'Delivery', 'TGX', 'TGS'],
    'Agrale': ['Marruá', 'A7500', 'A8700', 'A10000', 'Volare'],
    'Outros': ['Modelo não listado', 'Carro não listado', 'Caminhonete não listada', 'Caminhão não listado', 'Van não listada', 'Utilitário não listado'],
}
