# -*- coding: utf-8 -*-
# CORRIGE_ERRO_CATALOGO_MARCAS_20260901

BRANDS = {'Volkswagen': ['Gol',
                'Gol G2',
                'Gol G3',
                'Gol G4',
                'Gol G5',
                'Gol G6',
                'Gol G7',
                'Voyage',
                'Saveiro',
                'Saveiro Cross',
                'Parati',
                'Santana',
                'Polo',
                'Virtus',
                'T-Cross',
                'Nivus',
                'Fox',
                'CrossFox',
                'SpaceFox',
                'Jetta',
                'Golf',
                'Bora',
                'Amarok',
                'Kombi',
                'Fusca',
                'Up',
                'Taos',
                'Tiguan',
                'Passat',
                'Pointer',
                'Logus',
                'Apollo',
                'Brasília'],
 'Chevrolet': ['Celta',
               'Corsa',
               'Corsa Sedan',
               'Classic',
               'Prisma',
               'Onix',
               'Onix Plus',
               'Joy',
               'Montana',
               'S10',
               'Tracker',
               'Spin',
               'Cruze',
               'Astra',
               'Vectra',
               'Meriva',
               'Zafira',
               'Agile',
               'Cobalt',
               'Kadett',
               'Monza',
               'Omega',
               'Blazer',
               'Captiva',
               'Sonic',
               'Ipanema',
               'Chevette',
               'Opala',
               'Caravan',
               'D10',
               'D20',
               'Silverado',
               'Trailblazer'],
 'Fiat': ['Uno',
          'Uno Mille',
          'Mobi',
          'Palio',
          'Palio Weekend',
          'Siena',
          'Grand Siena',
          'Strada',
          'Toro',
          'Argo',
          'Cronos',
          'Punto',
          'Idea',
          'Fiorino',
          'Doblò',
          'Linea',
          'Pulse',
          'Fastback',
          'Tipo',
          'Tempra',
          'Brava',
          'Bravo',
          'Stilo',
          '500',
          '147',
          'Ducato',
          'Elba',
          'Prêmio',
          'Freemont',
          'Weekend'],
 'Ford': ['Ka',
          'Ka Sedan',
          'Fiesta',
          'Fiesta Sedan',
          'Focus',
          'Focus Sedan',
          'Fusion',
          'EcoSport',
          'Ranger',
          'Maverick',
          'Courier',
          'F-250',
          'Edge',
          'Territory',
          'Escort',
          'Verona',
          'Del Rey',
          'Corcel',
          'Belina',
          'Pampa',
          'Versailles',
          'Mondeo',
          'Mustang',
          'F-1000',
          'F-4000',
          'Cargo',
          'Transit',
          'Explorer'],
 'Hyundai': ['HB20', 'HB20S', 'HB20X', 'Creta', 'Tucson', 'ix35', 'Santa Fe', 'Azera', 'i30', 'Elantra', 'Sonata', 'Veloster', 'HR', 'H100', 'Kona'],
 'Toyota': ['Etios',
            'Etios Sedan',
            'Yaris',
            'Yaris Sedan',
            'Corolla',
            'Corolla Cross',
            'Hilux',
            'SW4',
            'RAV4',
            'Camry',
            'Bandeirante',
            'Prius',
            'Fielder',
            'Corona',
            'Land Cruiser'],
 'Honda': ['Fit', 'City', 'Civic', 'HR-V', 'WR-V', 'CR-V', 'Accord', 'Civic Si', 'ZR-V'],
 'Renault': ['Kwid', 'Sandero', 'Stepway', 'Logan', 'Duster', 'Duster Oroch', 'Captur', 'Clio', 'Fluence', 'Megane', 'Scénic', 'Kangoo', 'Master', 'Symbol', 'Laguna'],
 'Peugeot': ['106', '205', '206', '207', '208', '2008', '3008', '307', '308', '408', 'Partner', 'Boxer', 'Hoggar', 'RCZ'],
 'Citroën': ['C3', 'C3 Aircross', 'C4', 'C4 Lounge', 'C4 Cactus', 'Aircross', 'Xsara Picasso', 'C3 Picasso', 'Berlingo', 'Jumper', 'Jumpy', 'C5'],
 'Nissan': ['March', 'Versa', 'Kicks', 'Frontier', 'Sentra', 'Livina', 'Grand Livina', 'Tiida', 'X-Trail', 'Altima', 'Pathfinder'],
 'Jeep': ['Renegade', 'Compass', 'Commander', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
 'Mitsubishi': ['L200', 'L200 Triton', 'Pajero', 'Pajero TR4', 'ASX', 'Outlander', 'Eclipse Cross', 'Airtrek', 'Lancer', 'Mirage'],
 'Kia': ['Picanto', 'Cerato', 'Soul', 'Sportage', 'Sorento', 'Bongo', 'Carnival', 'Carens', 'Optima', 'Mohave'],
 'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'GLA', 'GLC', 'Sprinter', 'Accelo', 'Atego', 'Axor', 'Actros', '1113', '1313', '1620'],
 'BMW': ['Série 1', 'Série 3', 'Série 5', 'Série 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'Z4', 'M3', 'M5'],
 'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'Q3', 'Q5', 'Q7', 'TT', 'RS3'],
 'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'V40', 'FH', 'FM', 'VM', 'NL', 'N10', 'N12'],
 'RAM': ['Rampage', '1500', '2500', '3500', 'Classic'],
 'Caoa Chery': ['QQ', 'Tiggo 2', 'Tiggo 3x', 'Tiggo 5x', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5', 'Arrizo 6', 'Celer', 'Face'],
 'BYD': ['Dolphin', 'Dolphin Mini', 'Song Plus', 'Yuan Plus', 'Seal', 'Han', 'Tan', 'King', 'Shark'],
 'GWM': ['Haval H6', 'Ora 03', 'Poer', 'Tank 300'],
 'Jac': ['J2', 'J3', 'J5', 'J6', 'T40', 'T50', 'T60', 'T80', 'iEV20', 'iEV40'],
 'Land Rover': ['Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Freelander', 'Defender'],
 'Subaru': ['Forester', 'Impreza', 'XV', 'Outback', 'Legacy', 'WRX', 'Tribeca'],
 'Suzuki': ['Jimny', 'Vitara', 'Grand Vitara', 'S-Cross', 'Swift', 'SX4', 'Samurai'],
 'Iveco': ['Daily', 'Tector', 'Stralis', 'Hi-Way', 'Eurocargo'],
 'Scania': ['P', 'G', 'R', 'S', '113', '124', 'P360', 'R440', 'R450', 'R480'],
 'MAN': ['Constellation', 'Delivery', 'TGX', 'TGS'],
 'Agrale': ['Marruá', 'A7500', 'A8700', 'A10000', 'Volare'],
 'Outros': ['Modelo não listado', 'Carro não listado', 'Caminhonete não listada', 'Caminhão não listado', 'Van não listada', 'Utilitário não listado']}

CATALOGO = {'Óleos & Filtros': ['Troca de óleo 5W30', 'Troca de óleo 5W40', 'Filtro de óleo', 'Filtro de ar', 'Filtro de combustível', 'Aditivo do radiador', 'Troca de óleo 0W16', 'Troca de óleo 0W20', 'Troca de óleo 0W30', 'Troca de óleo 0W40', 'Troca de óleo 5W20', 'Troca de óleo 10W30', 'Troca de óleo 10W40', 'Troca de óleo 15W40', 'Troca de óleo 20W50', 'Troca de óleo 15W40 Diesel', 'Troca de óleo 5W30 C3 (Low SAPS)', 'Troca de óleo 5W40 C3 (Low SAPS)', 'Óleo 0W16 Sintético 1L (Castrol)', 'Óleo 0W16 Sintético 4L (Castrol)', 'Óleo 0W16 Sintético 1L (Mobil)', 'Óleo 0W16 Sintético 4L (Mobil)', 'Óleo 0W16 Sintético 1L (Motul)', 'Óleo 0W16 Sintético 4L (Motul)', 'Óleo 0W16 Sintético 1L (Shell)', 'Óleo 0W16 Sintético 4L (Shell)', 'Óleo 0W16 Sintético 1L (Ipiranga)', 'Óleo 0W16 Sintético 4L (Ipiranga)', 'Óleo 0W20 Sintético 1L (Castrol)', 'Óleo 0W20 Sintético 4L (Castrol)', 'Óleo 0W20 Sintético 1L (Mobil)', 'Óleo 0W20 Sintético 4L (Mobil)', 'Óleo 0W20 Sintético 1L (Motul)', 'Óleo 0W20 Sintético 4L (Motul)', 'Óleo 0W20 Sintético 1L (Shell)', 'Óleo 0W20 Sintético 4L (Shell)', 'Óleo 0W20 Sintético 1L (Ipiranga)', 'Óleo 0W20 Sintético 4L (Ipiranga)', 'Óleo 0W30 Sintético 1L (Castrol)', 'Óleo 0W30 Sintético 4L (Castrol)', 'Óleo 0W30 Sintético 1L (Mobil)', 'Óleo 0W30 Sintético 4L (Mobil)', 'Óleo 0W30 Sintético 1L (Motul)', 'Óleo 0W30 Sintético 4L (Motul)', 'Óleo 0W30 Sintético 1L (Shell)', 'Óleo 0W30 Sintético 4L (Shell)', 'Óleo 0W30 Sintético 1L (Ipiranga)', 'Óleo 0W30 Sintético 4L (Ipiranga)', 'Óleo 0W40 Sintético 1L (Castrol)', 'Óleo 0W40 Sintético 4L (Castrol)', 'Óleo 0W40 Sintético 1L (Mobil)', 'Óleo 0W40 Sintético 4L (Mobil)', 'Óleo 0W40 Sintético 1L (Motul)', 'Óleo 0W40 Sintético 4L (Motul)', 'Óleo 0W40 Sintético 1L (Shell)', 'Óleo 0W40 Sintético 4L (Shell)', 'Óleo 0W40 Sintético 1L (Ipiranga)', 'Óleo 0W40 Sintético 4L (Ipiranga)', 'Óleo 5W20 Sintético 1L (Castrol)', 'Óleo 5W20 Sintético 4L (Castrol)', 'Óleo 5W20 Sintético 1L (Mobil)', 'Óleo 5W20 Sintético 4L (Mobil)', 'Óleo 5W20 Sintético 1L (Motul)', 'Óleo 5W20 Sintético 4L (Motul)', 'Óleo 5W20 Sintético 1L (Shell)', 'Óleo 5W20 Sintético 4L (Shell)', 'Óleo 5W20 Sintético 1L (Ipiranga)', 'Óleo 5W20 Sintético 4L (Ipiranga)', 'Óleo 5W30 Sintético 1L (Castrol)', 'Óleo 5W30 Sintético 4L (Castrol)', 'Óleo 5W30 Sintético 1L (Mobil)', 'Óleo 5W30 Sintético 4L (Mobil)', 'Óleo 5W30 Sintético 1L (Motul)', 'Óleo 5W30 Sintético 4L (Motul)', 'Óleo 5W30 Sintético 1L (Shell)', 'Óleo 5W30 Sintético 4L (Shell)', 'Óleo 5W30 Sintético 1L (Ipiranga)', 'Óleo 5W30 Sintético 4L (Ipiranga)', 'Óleo 5W30 C3 (Low SAPS) Sintético 1L (Castrol)', 'Óleo 5W30 C3 (Low SAPS) Sintético 4L (Castrol)', 'Óleo 5W30 C3 (Low SAPS) Sintético 1L (Mobil)', 'Óleo 5W30 C3 (Low SAPS) Sintético 4L (Mobil)', 'Óleo 5W30 C3 (Low SAPS) Sintético 1L (Motul)', 'Óleo 5W30 C3 (Low SAPS) Sintético 4L (Motul)', 'Óleo 5W30 C3 (Low SAPS) Sintético 1L (Shell)', 'Óleo 5W30 C3 (Low SAPS) Sintético 4L (Shell)', 'Óleo 5W30 C3 (Low SAPS) Sintético 1L (Ipiranga)', 'Óleo 5W30 C3 (Low SAPS) Sintético 4L (Ipiranga)', 'Óleo 5W40 Sintético 1L (Castrol)', 'Óleo 5W40 Sintético 4L (Castrol)', 'Óleo 5W40 Sintético 1L (Mobil)', 'Óleo 5W40 Sintético 4L (Mobil)', 'Óleo 5W40 Sintético 1L (Motul)', 'Óleo 5W40 Sintético 4L (Motul)', 'Óleo 5W40 Sintético 1L (Shell)', 'Óleo 5W40 Sintético 4L (Shell)', 'Óleo 5W40 Sintético 1L (Ipiranga)', 'Óleo 5W40 Sintético 4L (Ipiranga)', 'Óleo 5W40 C3 (Low SAPS) Sintético 1L (Castrol)', 'Óleo 5W40 C3 (Low SAPS) Sintético 4L (Castrol)', 'Óleo 5W40 C3 (Low SAPS) Sintético 1L (Mobil)', 'Óleo 5W40 C3 (Low SAPS) Sintético 4L (Mobil)', 'Óleo 5W40 C3 (Low SAPS) Sintético 1L (Motul)', 'Óleo 5W40 C3 (Low SAPS) Sintético 4L (Motul)', 'Óleo 5W40 C3 (Low SAPS) Sintético 1L (Shell)', 'Óleo 5W40 C3 (Low SAPS) Sintético 4L (Shell)', 'Óleo 5W40 C3 (Low SAPS) Sintético 1L (Ipiranga)', 'Óleo 5W40 C3 (Low SAPS) Sintético 4L (Ipiranga)', 'Óleo 10W30 Semissintético 1L (Castrol)', 'Óleo 10W30 Semissintético 4L (Castrol)', 'Óleo 10W30 Semissintético 1L (Mobil)', 'Óleo 10W30 Semissintético 4L (Mobil)', 'Óleo 10W30 Semissintético 1L (Motul)', 'Óleo 10W30 Semissintético 4L (Motul)', 'Óleo 10W30 Semissintético 1L (Shell)', 'Óleo 10W30 Semissintético 4L (Shell)', 'Óleo 10W30 Semissintético 1L (Ipiranga)', 'Óleo 10W30 Semissintético 4L (Ipiranga)', 'Óleo 10W40 Semissintético 1L (Castrol)', 'Óleo 10W40 Semissintético 4L (Castrol)', 'Óleo 10W40 Semissintético 1L (Mobil)', 'Óleo 10W40 Semissintético 4L (Mobil)', 'Óleo 10W40 Semissintético 1L (Motul)', 'Óleo 10W40 Semissintético 4L (Motul)', 'Óleo 10W40 Semissintético 1L (Shell)', 'Óleo 10W40 Semissintético 4L (Shell)', 'Óleo 10W40 Semissintético 1L (Ipiranga)', 'Óleo 10W40 Semissintético 4L (Ipiranga)', 'Óleo 15W40 Mineral 1L (Castrol)', 'Óleo 15W40 Mineral 4L (Castrol)', 'Óleo 15W40 Mineral 1L (Mobil)', 'Óleo 15W40 Mineral 4L (Mobil)', 'Óleo 15W40 Mineral 1L (Motul)', 'Óleo 15W40 Mineral 4L (Motul)', 'Óleo 15W40 Mineral 1L (Shell)', 'Óleo 15W40 Mineral 4L (Shell)', 'Óleo 15W40 Mineral 1L (Ipiranga)', 'Óleo 15W40 Mineral 4L (Ipiranga)', 'Óleo 15W40 Diesel Mineral 1L (Castrol)', 'Óleo 15W40 Diesel Mineral 4L (Castrol)', 'Óleo 15W40 Diesel Mineral 1L (Mobil)', 'Óleo 15W40 Diesel Mineral 4L (Mobil)', 'Óleo 15W40 Diesel Mineral 1L (Motul)', 'Óleo 15W40 Diesel Mineral 4L (Motul)', 'Óleo 15W40 Diesel Mineral 1L (Shell)', 'Óleo 15W40 Diesel Mineral 4L (Shell)', 'Óleo 15W40 Diesel Mineral 1L (Ipiranga)', 'Óleo 15W40 Diesel Mineral 4L (Ipiranga)', 'Óleo 20W50 Mineral 1L (Castrol)', 'Óleo 20W50 Mineral 4L (Castrol)', 'Óleo 20W50 Mineral 1L (Mobil)', 'Óleo 20W50 Mineral 4L (Mobil)', 'Óleo 20W50 Mineral 1L (Motul)', 'Óleo 20W50 Mineral 4L (Motul)', 'Óleo 20W50 Mineral 1L (Shell)', 'Óleo 20W50 Mineral 4L (Shell)', 'Óleo 20W50 Mineral 1L (Ipiranga)', 'Óleo 20W50 Mineral 4L (Ipiranga)'], 'Suspensão': ['Amortecedor dianteiro', 'Amortecedor traseiro', 'Kit amortecedor dianteiro', 'Kit amortecedor traseiro', 'Coxim superior do amortecedor', 'Batente do amortecedor', 'Coifa do amortecedor', 'Mola helicoidal dianteira', 'Mola helicoidal traseira', 'Bieleta da barra estabilizadora', 'Barra estabilizadora', 'Bucha da barra estabilizadora', 'Bandeja de suspensão', 'Bucha da bandeja', 'Pivô (pivot) de suspensão', 'Bucha do eixo traseiro', 'Coxim do agregado (subframe)', 'Rolamento do cubo', 'Cubo de roda', 'Manga de eixo'], 'Freios': ['Pastilha dianteira', 'Pastilha traseira', 'Disco de freio', 'Tambores', 'Fluido de freio', 'Sangria do sistema'], 'Elétrica': ['Bateria', 'Alternador', 'Motor de partida', 'Lâmpada H7', 'Sensor ABS'], 'Arrefecimento': ['Radiador', 'Bomba d’água', 'Válvula termostática', 'Reservatório', 'Mangueira do radiador'], 'Transmissão': ['Embreagem (kit)', 'Óleo de câmbio', 'Cabo de embreagem'], 'Pneus & Geometria': ['Pneu 175/65R14', 'Pneu 205/55R16', 'Alinhamento', 'Balanceamento', 'Cambagem'], 'Limpeza & Ar': ['Higienização do ar-condicionado', 'Filtro de cabine', 'Limpeza de bicos'], 'Outros': ['Diagnóstico via scanner', 'Mão de obra geral'], 'Correias': ['Correia dentada (kit)', 'Correia dentada (apenas correia)', 'Tensor da correia dentada', 'Esticador da correia dentada', 'Correia do alternador (poly V)', 'Tensor da correia do alternador', 'Correia do ar-condicionado', 'Tensor da correia do ar-condicionado', 'Correia da direção hidráulica', 'Tensor da correia da direção hidráulica', 'Kit correias auxiliares (alternador/ar/direção)', 'Polia guia', 'Polia do alternador', 'Verificação e ajuste de tensionamento das correias'], 'Motor': ['Vela de ignição', 'Jogo de velas', 'Cabo de vela', 'Bobina de ignição', 'Junta da tampa de válvulas', 'Junta do cárter', 'Jogo de juntas (motor)', 'Retentor do virabrequim (dianteiro)', 'Retentor do virabrequim (traseiro)', 'Retentor do comando de válvulas', 'Bomba de óleo', 'Bico injetor', 'Sensor MAP', 'Sensor MAF', 'Sensor TPS', 'Sonda lambda (pré)', 'Sonda lambda (pós)', 'Válvula PCV', 'Coxim do motor', 'Junta do coletor de admissão', 'Junta do coletor de escape']}

ESTOQUE_BASICO = [['Óleo 5W30 (Petronas)', 'Lubrificantes', 0, 0], ['Óleo 5W40 (Elaion)', 'Lubrificantes', 0, 0], ['Óleo 0W20 (Uni)', 'Lubrificantes', 0, 0], ['Óleo 15W40 (Petronas)', 'Lubrificantes', 0, 0], ['Óleo 20W50', 'Lubrificantes', 0, 0], ['Óleo 5W40 (Castrol)', 'Lubrificantes', 0, 0], ['Óleo 0W20 700xs (Petronas)', 'Lubrificantes', 0, 0], ['Óleo 5W30 Nexo 1 (Petronas)', 'Lubrificantes', 0, 0], ['Óleo 5W20 (Havoline)', 'Lubrificantes', 0, 0], ['Óleo 0W20 (Elaion)', 'Lubrificantes', 0, 0], ['Óleo 5W30 (I9lub)', 'Lubrificantes', 0, 0], ['Óleo 5W30 Nexo 2', 'Lubrificantes', 0, 0], ['TM 1', 'Filtros lubrificantes', 0, 0], ['TM 2', 'Filtros lubrificantes', 0, 0], ['TM 3', 'Filtros lubrificantes', 0, 0], ['TM 4', 'Filtros lubrificantes', 0, 0], ['TM 5', 'Filtros lubrificantes', 0, 0], ['Psh 560', 'Filtros lubrificantes', 0, 0], ['Psh 545', 'Filtros lubrificantes', 0, 0], ['Psh 45', 'Filtros lubrificantes', 0, 0], ['Psh 56', 'Filtros lubrificantes', 0, 0], ['Psh 129', 'Filtros lubrificantes', 0, 0], ['PEL 803', 'Filtros lubrificantes', 0, 0], ['PEL 119', 'Filtros lubrificantes', 0, 0], ['WO 132', 'Filtros lubrificantes', 0, 0], ['Psh 47', 'Filtros lubrificantes', 0, 0], ['Psh 55', 'Filtros lubrificantes', 0, 0], ['Psh 619', 'Filtros lubrificantes', 0, 0], ['Psh 612', 'Filtros lubrificantes', 0, 0], ['Psh 145', 'Filtros lubrificantes', 0, 0], ['Psh 134', 'Filtros lubrificantes', 0, 0], ['Psh 77', 'Filtros lubrificantes', 0, 0], ['PE 103', 'Filtros lubrificantes', 0, 0], ['Psh 565', 'Filtros lubrificantes', 0, 0], ['Psh 615', 'Filtros lubrificantes', 0, 0], ['Psh 818', 'Filtros lubrificantes', 0, 0], ['G10811', 'Filtros de combustível', 0, 0], ['G10711', 'Filtros de combustível', 0, 0], ['G10617', 'Filtros de combustível', 0, 0], ['G12217', 'Filtros de combustível', 0, 0], ['G15017', 'Filtros de combustível', 0, 0], ['G10417', 'Filtros de combustível', 0, 0], ['G14017', 'Filtros de combustível', 0, 0], ['G16017', 'Filtros de combustível', 0, 0], ['AG 68', 'Filtros de combustível', 0, 0], ['GU 86', 'Filtros de combustível', 0, 0], ['G141', 'Filtros de combustível', 0, 0], ['ARL 4150', 'Filtros de ar', 0, 0], ['ARL 8840', 'Filtros de ar', 0, 0], ['ARL 8839', 'Filtros de ar', 0, 0], ['ARL 6093', 'Filtros de ar', 0, 0], ['ARL 8825', 'Filtros de ar', 0, 0], ['ARL 6076', 'Filtros de ar', 0, 0], ['ARL 4154', 'Filtros de ar', 0, 0], ['ARL 6071', 'Filtros de ar', 0, 0], ['ARL 6095', 'Filtros de ar', 0, 0], ['ARL 4152', 'Filtros de ar', 0, 0], ['ARL 4161', 'Filtros de ar', 0, 0], ['ARL 6091', 'Filtros de ar', 0, 0], ['ARL 6080', 'Filtros de ar', 0, 0], ['ARL 8834', 'Filtros de ar', 0, 0], ['ARL 4247', 'Filtros de ar', 0, 0], ['ARL 8820', 'Filtros de ar', 0, 0], ['ART 6090', 'Filtros de ar', 0, 0], ['AR 9621', 'Filtros de ar', 0, 0], ['ARL 6096', 'Filtros de ar', 0, 0], ['ARL 9608', 'Filtros de ar', 0, 0], ['FAP 9288', 'Filtros de ar', 0, 0], ['ARL 8832', 'Filtros de ar', 0, 0], ['ARL 8825', 'Filtros de ar', 0, 0], ['ARL 1034', 'Filtros de ar', 0, 0], ['ARL 4155', 'Filtros de ar', 0, 0], ['ARL 2203', 'Filtros de ar', 0, 0], ['ARL 6074', 'Filtros de ar', 0, 0], ['ARL 1035', 'Filtros de ar', 0, 0], ['ARL 8829', 'Filtros de ar', 0, 0], ['ART 8860', 'Filtros de ar', 0, 0], ['ARL 4161', 'Filtros de ar', 0, 0], ['ARS 1029', 'Filtros de ar', 0, 0], ['ARL 1658', 'Filtros de ar', 0, 0], ['AR 7705', 'Filtros de ar', 0, 0], ['ARL 6090', 'Filtros de ar', 0, 0], ['ARL 4160', 'Filtros de ar', 0, 0], ['ARL 2207', 'Filtros de ar', 0, 0], ['ARL 2340', 'Filtros de ar', 0, 0], ['ARL 2204', 'Filtros de ar', 0, 0], ['ART 9613', 'Filtros de ar', 0, 0], ['ARL 1043', 'Filtros de ar', 0, 0], ['ART 9614', 'Filtros de ar', 0, 0], ['AR 2952', 'Filtros de ar', 0, 0], ['AR 6046', 'Filtros de ar', 0, 0], ['AR 6093', 'Filtros de ar', 0, 0], ['ARL 2238', 'Filtros de ar', 0, 0], ['ART 9615', 'Filtros de ar', 0, 0], ['ACP 105', 'Filtros de ar condicionado', 0, 0], ['ACP 300', 'Filtros de ar condicionado', 0, 0], ['ACP 303', 'Filtros de ar condicionado', 0, 0], ['ACP 103', 'Filtros de ar condicionado', 0, 0], ['ACP 311', 'Filtros de ar condicionado', 0, 0], ['ACP 126', 'Filtros de ar condicionado', 0, 0], ['ACP 887', 'Filtros de ar condicionado', 0, 0], ['ACP 312', 'Filtros de ar condicionado', 0, 0], ['ACP 003', 'Filtros de ar condicionado', 0, 0], ['ACP 906', 'Filtros de ar condicionado', 0, 0], ['ACP 008', 'Filtros de ar condicionado', 0, 0], ['ACP 305', 'Filtros de ar condicionado', 0, 0], ['ACP 972', 'Filtros de ar condicionado', 0, 0], ['ACP 709', 'Filtros de ar condicionado', 0, 0], ['ACP 001', 'Filtros de ar condicionado', 0, 0], ['ACP 888', 'Filtros de ar condicionado', 0, 0], ['ACP 205', 'Filtros de ar condicionado', 0, 0], ['ACP 721', 'Filtros de ar condicionado', 0, 0], ['ACP 727', 'Filtros de ar condicionado', 0, 0], ['JFA 0192', 'Filtros de ar condicionado', 0, 0], ['Jogo velas Gol H — BKR6ESB-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas Fire — BKR6E-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas — BR6ES-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas — B7ES-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas — BPR6E-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas — BKR6E-09', 'Velas e cabos de vela', 0, 0], ['Jogo velas — BPR5EY-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas — BPR6EY-D', 'Velas e cabos de vela', 0, 0], ['Jogo velas Magnet — BR6ES-D', 'Velas e cabos de vela', 0, 0], ['Jogo de velas Evo — ZKR8B10', 'Velas e cabos de vela', 0, 0], ['Cabo velas VW Bosch — F00099C125', 'Velas e cabos de vela', 0, 0], ['Cabo velas Fiat Bosch Fire — F00099C320', 'Velas e cabos de vela', 0, 0], ['Cabo velas VW Magnet — CVMP8502', 'Velas e cabos de vela', 0, 0], ['Cabo velas Magnet — CVMG7302', 'Velas e cabos de vela', 0, 0], ['Cabo velas Fiat Magnet — CVMT9902', 'Velas e cabos de vela', 0, 0], ['Cabo velas Fiat Evo — F00099C146', 'Velas e cabos de vela', 0, 0], ['Cabo velas — F00099C012', 'Velas e cabos de vela', 0, 0], ['Cabo velas — F00099C612', 'Velas e cabos de vela', 0, 0], ['Cabo velas — F00099C110', 'Velas e cabos de vela', 0, 0], ['Cabo velas — F00099C117', 'Velas e cabos de vela', 0, 0], ['Cabo velas — F00099C143', 'Velas e cabos de vela', 0, 0], ['Jogo velas Gol 1.0 — BKR5EY', 'Velas e cabos de vela', 0, 0], ['Cabo velas Gol 1.0 — 9295080044', 'Velas e cabos de vela', 0, 0], ['Jogo velas Etorq — KR8B-10D', 'Velas e cabos de vela', 0, 0], ['Jogo cabo velas — F00099C142', 'Velas e cabos de vela', 0, 0], ['Jogo cabo velas (Celta) — NGR', 'Velas e cabos de vela', 0, 0], ['Correia dentada Gol (Dayco 76,50)', 'Correias e esticadores', 0, 0], ['Correia 129P85220H', 'Correias e esticadores', 0, 0], ['Correia 124P85220H', 'Correias e esticadores', 0, 0], ['Correia 111SP170H', 'Correias e esticadores', 0, 0], ['Correia 1295x180H', 'Correias e esticadores', 0, 0], ['Correia 3495TP8M254H', 'Correias e esticadores', 0, 0], ['Correia 3PK796EE (ar condicionado)', 'Correias e esticadores', 0, 0], ['Correia 6PK1200EE (alternador)', 'Correias e esticadores', 0, 0], ['Correia 5PK1795', 'Correias e esticadores', 0, 0], ['Correia 5PK1170', 'Correias e esticadores', 0, 0], ['Correia 1175T0', 'Correias e esticadores', 0, 0], ['Correia 1315HP170H', 'Correias e esticadores', 0, 0], ['Correia 1175150', 'Correias e esticadores', 0, 0], ['Correia 4PK9673 (alternador)', 'Correias e esticadores', 0, 0], ['Correia 5PK1190 (alternador)', 'Correias e esticadores', 0, 0], ['Correia 3PK905 (direção)', 'Correias e esticadores', 0, 0], ['Correia 6PK1795', 'Correias e esticadores', 0, 0], ['Correia 5PK1030', 'Correias e esticadores', 0, 0], ['Correia 5PK1185', 'Correias e esticadores', 0, 0], ['Correia 5PK1175 (alternador)', 'Correias e esticadores', 0, 0], ['Correia 5PK1180', 'Correias e esticadores', 0, 0], ['Correia 5PK1460', 'Correias e esticadores', 0, 0], ['Correia 10A0925C', 'Correias e esticadores', 0, 0], ['Correia 3PK890EE', 'Correias e esticadores', 0, 0], ['Correia 1465TP8M200H', 'Correias e esticadores', 0, 0], ['Correia 6PK2270', 'Correias e esticadores', 0, 0], ['Correia 6PK870', 'Correias e esticadores', 0, 0], ['Correia 6PK1700', 'Correias e esticadores', 0, 0], ['Polia do alternador 1143', 'Correias e esticadores', 0, 0], ['Polia do alternador 1152', 'Correias e esticadores', 0, 0], ['Tensor 7796 GM', 'Correias e esticadores', 0, 0], ['Tensor 7704 Fiat', 'Correias e esticadores', 0, 0], ['Tensor 7736 Gol', 'Correias e esticadores', 0, 0], ['Tensor 7741 Fiat', 'Correias e esticadores', 0, 0], ['Tensor 7792 GM', 'Correias e esticadores', 0, 0], ['Tensor 7782 Gol', 'Correias e esticadores', 0, 0], ['Tensor 7732 Fiat', 'Correias e esticadores', 0, 0], ['Tensor RT6367 Fiat', 'Correias e esticadores', 0, 0], ['Tensor RT6009L17', 'Correias e esticadores', 0, 0], ['Tensor RT6526 Fiat', 'Correias e esticadores', 0, 0], ['Tensor RT0816 Gol', 'Correias e esticadores', 0, 0], ['Tensor RT0817 Gol', 'Correias e esticadores', 0, 0], ['Tensor RT6180 Gol', 'Correias e esticadores', 0, 0], ['Tensor RT6027 Gol', 'Correias e esticadores', 0, 0], ['Polia esticador GM 1139', 'Correias e esticadores', 0, 0], ['Polia esticador GM 1129', 'Correias e esticadores', 0, 0], ['Polia esticador Gol 1114', 'Correias e esticadores', 0, 0], ['Rolamento esticador GM RT6026', 'Correias e esticadores', 0, 0], ['Polia do alternador Cobalt', 'Correias e esticadores', 0, 0], ['Polia do alternador 1180', 'Correias e esticadores', 0, 0], ['Correia 3PK895EE', 'Correias e esticadores', 0, 0], ['Pastilha de freio — P.85', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.1346', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.92', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.73', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.58', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.88', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.362', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.1482', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.368', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.60', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.94', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.82', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.65', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.90', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.54', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.25', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.68', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.55', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.46', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.367', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1100', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.51', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.23', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/588B', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1584', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.42', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.66', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD.28', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — SYL', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.81', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.42', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1669', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1689', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1696', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — 3115', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — 4381', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.1432', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.4082', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1795', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.89', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.17', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — PD/1480', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.87', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — F193CP', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — CB149-CP', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — F191-CP', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — FD/61CPA', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — F1219-CPA', 'Pastilhas/Sapatas', 0, 0], ['Pastilha de freio — P.47', 'Pastilhas/Sapatas', 0, 0], ['Sapata de freio — F1330', 'Pastilhas/Sapatas', 0, 0], ['Strada 1.4 dianteiro', 'Amortecedores', 0, 0], ['Strada 1.4 traseiro', 'Amortecedores', 0, 0], ['Palio Powershock dianteiro', 'Amortecedores', 0, 0], ['Celta dianteiro', 'Amortecedores', 0, 0], ['Celta traseiro', 'Amortecedores', 0, 0], ['Gol G3 dianteiro', 'Amortecedores', 0, 0], ['Palio traseiro', 'Amortecedores', 0, 0], ['Gol G3 traseiro', 'Amortecedores', 0, 0], ['Óleo 10W30 200ml', 'Diversos', 0, 0], ['Óleo 10W40 200ml', 'Diversos', 0, 0], ['Óleo 10W30 500ml', 'Diversos', 0, 0], ['Óleo 10W40 500ml', 'Diversos', 0, 0], ['Óleo caixa 90', 'Diversos', 0, 0], ['Óleo direção hidráulica ATF10', 'Diversos', 0, 0], ['Óleo direção SAE 440', 'Diversos', 0, 0], ['Aditivo Teccool', 'Diversos', 0, 0], ['Aditivo Petronas', 'Diversos', 0, 0], ['Limpa radiador Paraflu', 'Diversos', 0, 0], ['Graxa 1kg', 'Diversos', 0, 0], ['Querosene', 'Diversos', 0, 0], ['Silenciador de freio', 'Diversos', 0, 0], ['Desengripante', 'Diversos', 0, 0], ['Água desmineralizada', 'Diversos', 0, 0], ['Limpa ar condicionado', 'Diversos', 0, 0], ['Vela de ignição', 'Motor', 16, 29.9], ['Jogo de velas', 'Motor', 4, 119.9], ['Cabo de vela', 'Motor', 4, 89.9], ['Bobina de ignição', 'Motor', 4, 249.9], ['Junta da tampa de válvulas', 'Motor', 4, 49.9], ['Junta do cárter', 'Motor', 2, 79.9], ['Jogo de juntas (motor)', 'Motor', 2, 399.9], ['Retentor do virabrequim (dianteiro)', 'Motor', 4, 39.9], ['Retentor do virabrequim (traseiro)', 'Motor', 4, 59.9], ['Retentor do comando de válvulas', 'Motor', 4, 39.9], ['Bomba de óleo', 'Motor', 2, 349.9], ['Bico injetor', 'Motor', 8, 199.9], ['Sensor MAP', 'Motor', 4, 129.9], ['Sensor MAF', 'Motor', 2, 299.9], ['Sensor TPS', 'Motor', 4, 89.9], ['Sonda lambda (pré)', 'Motor', 2, 349.9], ['Sonda lambda (pós)', 'Motor', 2, 349.9], ['Válvula PCV', 'Motor', 4, 79.9], ['Coxim do motor', 'Motor', 2, 199.9], ['Junta do coletor de admissão', 'Motor', 4, 49.9], ['Junta do coletor de escape', 'Motor', 4, 54.9]]
